DROP TABLE IF EXISTS damages CASCADE;
DROP TABLE IF EXISTS item_colors CASCADE;
DROP TABLE IF EXISTS item_models CASCADE;
DROP TABLE IF EXISTS item_brands CASCADE;
DROP TABLE IF EXISTS item_types CASCADE;